spring:
  application:
    name: api
  

  
  # PostgreSQL 데이터소스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/aidb
    username: Aiion
    password: aiion4man
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create   # create, create-drop, update, validate 중 선택
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  
  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# 서버 포트 설정
server:
  port: 8080

